Model: 
  Name: HuggingFaceH4/zephyr-7b-alpha
  Description: A 7B parameter GPT-like model fine-tuned on a mix of publicly available, synthetic datasets
  Language: Primarily English 
  License: MIT
  Finetuned_from: mistralai/Mistral-7B-v0.1
  Huggingface_link: https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha
  max_token: 32768
  sliding_window: 4096


Deployment: 
  model_download_path: ~/.cache/models
  artifact_path: llama_deployment_uc
  quantization: 8_bit
  parameter_size: 7
  unity_catalog: 
    unity_catalog_uri: databricks-uc
    unity_catalog_name: capgemini
    unity_catalog_schema: chatbot 
  parameters: 
    temperature: 0.1
    max_token: 150

Examples: 
  input_example: Hello, how are you?
  output_example: How can I help you. 


pip_requirements: 
  - pandas==1.4.4
  - torch==2.1.0
  - transformers==4.34.0
  - accelerate==0.23.0
  - bitsandbytes==0.41.1
  - tiktoken==0.5.1

Secrete:
  huggingface_hub: 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
